### ISSUE TITLE
Web hooks & monitor dependencies for Repos I'm an admin for?

### ISSUE THREAD

**Issue by kevmoo** [librariesio/support#67]
I see these options for repos under my account.
Would be nice to see these for repos I'm a member (admin? contributor?) for

**Comment by andrew** [comment]
@kevmoo right, those options only show for repositories where you have permission to create a webhook on GitHub so that Libraries can know when the repo has been updates, which in terms of GitHub permissions means you need to be "admin" on that org/team, I could show the option for contributor permissions but without the ability to set a web hook it doesn't really work as Libraries wouldn't know when the dependencies have changed on the repo.
